version: "3"
services:
  golang-app:
    image: lorenzodagostinorad/go-example:d691cca4496056dbac935d29e5969a35edcdfc33
    ports:
      - 8081:3000


  backend-build:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      - VERSION_API_ENDPOINT=golang-app
      - VERSION_API_PORT=3000
    depends_on:
      - golang-app