version: "3"
services:
  golang-app:
    image: lorenzodagostinorad/go-example:latest
    ports:
      - 8081:3000

  backend-build:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      - VERSION_API_ENDPOINT=127.0.0.1
      - VERSION_API_PORT=8081
    depends_on:
      - golang-app