version: "3"
services:
  golang-app:
    image: lorenzodagostinorad/go-example:latest
    environment:
      - PROD_SERVER_PORT=3000

  backend-build:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - VERSION_API_ENDPOINT=golang-app
      - VERSION_API_PORT=3000
    depends_on:
      - golang-app